# Essai de bout en bout de l'outil en ligne de commande.
file(REMOVE_RECURSE ${DOSSIER})
file(MAKE_DIRECTORY ${DOSSIER})
execute_process(COMMAND ${OUTIL} exemple ${DOSSIER}/exemple.prom.json RESULT_VARIABLE r1)
execute_process(COMMAND ${OUTIL} verifier ${DOSSIER}/exemple.prom.json RESULT_VARIABLE r2)
execute_process(COMMAND ${OUTIL} exporter ${DOSSIER}/exemple.prom.json ${DOSSIER}/dossier RESULT_VARIABLE r3)
if(NOT r1 EQUAL 0 OR NOT r2 EQUAL 0 OR NOT r3 EQUAL 0)
  message(FATAL_ERROR "Échec de l'outil : ${r1} ${r2} ${r3}")
endif()
foreach(f boitier.step boitier.stl couvercle.stl projet.prom.json)
  if(NOT EXISTS ${DOSSIER}/dossier/${f})
    message(FATAL_ERROR "Fichier manquant : ${f}")
  endif()
endforeach()
